package:
  name: graph-tool-gcc5
  version: 2.18

source:
  git_url: https://github.com/count0/graph-tool
  git_rev: release-2.18

requirements:
  build:
    - python
    - boost1-gcc5
    - zlib
    - gcc-5
    - numpy
    - scipy
    - cgal-boost-gcc5
    - expat
    - sparsehash-gcc5
    - icu	[unix]
    - cairomm
    - pycairo

  run:
    - python
    - boost1-gcc5
    - libgcc-5
    - zlib
    - numpy
    - scipy
    - matplotlib
    - cgal-boost-gcc5
    - expat
    - sparsehash-gcc5
    - icu	[unix]
    - cairo
    - cairomm
    - pycairo
    - pygobject
    - freetype
    - libpng
    - fontconfig
    - librsvg

test:
  imports:
    - graph_tool
    - graph_tool.all

about:
  home: https://graph-tool.skewed.de
  license: GPLv3
