package:
  name: graph-tool-gcc5
  version: 2.18

source:
  git_url: https://github.com/count0/graph-tool
  git_rev: release-2.18

requirements:
  build:
    - python
    - boost1-gcc5
    - zlib
    - bzip2
    - gcc-5
    - numpy
    - scipy
    - cgal-boost-gcc5
    - expat
    - sparsehash-gcc5
    - cairomm
    - pycairo

  run:
    - python
    - boost1-gcc5
    - libgcc-5
    - zlib
    - bzip2
    - numpy
    - scipy
    - matplotlib
    - cgal-boost-gcc5
    - expat
    - sparsehash-gcc5
    - cairo
    - cairomm
    - pycairo
    - pygobject
    - pango

test:
  imports:
    - graph_tool
    - graph_tool.all
  commands:
    - conda inspect linkages -p ${PREFIX} graph-tool-gcc5  # [not win]
    - conda inspect objects -p ${PREFIX} graph-tool-gcc5  # [osx]

about:
  home: https://graph-tool.skewed.de
  license: GPLv3
