package:
  name: librdf
  version: 1.0.18
source:
  git_url: https://github.com/dajobe/librdf
  git_rev: master
build:
  number: 0
requirements:
  build:
    - rasqal
    - openssl
    - postgresql
    - sqlite
  run:
    - rasqal
    - openssl
    - sqlite
test:
  commands:
    - conda inspect linkages -p ${PREFIX} librdf  # [not win]
    - conda inspect objects -p ${PREFIX} librdf  # [osx] 
about:
  home: https://github.com/dajobe/librdf
  license: Apache2
