{% set name = "hdtcpp" %}
{% set version = "1.3.3" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  git_url: https://github.com/ptorrestr/hdt-cpp-1
  git_rev: develop

build:
  number: 0

requirements:
  build:
    - zlib
    - serd

  run:
    - zlib
    - serd

test:
  commands:
    - conda inspect linkages -p ${PREFIX} hdtcpp  # [not win]
    - conda inspect objects -p ${PREFIX} hdtcpp  # [osx]

about:
  home: https://github.com/hdtrdf/hdt-cpp
  license: GPLv2
