package:
  name: hdtcpp
  version: 1.1.3

source:
  git_url: https://github.com/ptorrestr/hdt-cpp
  git_rev: 1.1.3

requirements:
  build:
    - gcc-5
    - zlib
    - bzip2

  run:
    - libgcc-5
    - zlib
    - bzip2

test:
  commands:
    - conda inspect linkages -p ${PREFIX} hdtcpp  # [not win]
    - conda inspect objects -p ${PREFIX} hdtcpp  # [osx]

about:
  home: https://github.com/ptorrestr/hdt-cpp
  license: GPLv2
