{% set name = "hdtcpp" %}
{% set version = "1.1.2" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  git_url: https://github.com/rdfhdt/hdt-cpp
  git_rev: develop

build:
  number: 0

requirements:
  build:
    - autoconf
    - automake
    - binutils    # [not osx] 
    - gcc-6
    - zlib
    - serd

  run:
    - libgcc-6
    - zlib
    - serd

test:
  commands:
    - conda inspect linkages -p ${PREFIX} hdtcpp  # [not win]
    - conda inspect objects -p ${PREFIX} hdtcpp  # [osx]

about:
  home: https://github.com/hdtrdf/hdt-cpp
  license: GPLv2
