package:
  name: sparsehash-gcc5
  version: 2.0.3

source:
  git_url: https://github.com/sparsehash/sparsehash
  git_rev: sparsehash-2.0.3

requirements:
  build:
    - gcc-5

  run:
    - libgcc-5

about:
  home: https://github.com/sparsehash/sparsehash
