{% set version = "0.1" %}

package:
  name: cite2c
  version: {{ version }}

source:
  git_url: https://github.com/takluyver/cite2c
  git_rev: {{ version }}

requirements:
  build:
    - python
    - notebook >=4.2

  run:
    - python
    - notebook >=4.2

build:
  script: python -m cite2c.install

about:
  home: https://github.com/takluyver/cite2c
  license: MIT
