{% set version = "1.12.0" %}
{% set checksum = "5a09a3f604cec2ddb4dfcace28dbe74a53585585" %}
{% set checktype = "sha1" %}

package:
    name: cairomm-gcc5
    version: {{ version }}

source:
    fn: cairomm-{{ version }}.tar.gz
    url: https://www.cairographics.org/releases/cairomm-{{ version }}.tar.gz
    {{ checktype }}: {{ checksum }}

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - gcc-5
    - cairo
    - libsigcpp
    - libpng >=1.6.23,<1.7
    - pkg-config
    - toolchain
  run:
    - libgcc-5
    - cairo
    - libsigcpp
    - libpng >=1.6.23,<1.7

test:
    commands:
        - test -f $PREFIX/lib/libcairomm-1.0.a
        - test -f $PREFIX/lib/libcairomm-1.0.so          # [linux]
        - test -f $PREFIX/lib/libcairomm-1.0.dylib       # [osx]
        - test -f $PREFIX/lib/libcairomm-1.0.la

about:
    home: http://cairographics.org/
    license: LGPL 2.1 and MPL 1.1
    summary: "cairomm is a C++ wrapper for the cairo graphics library"

extra:
    recipe-maintainers:
        - vgauthier
