package:
  name: librdf-python-binding
  version: 1.0.18
source:
  git_url: https://github.com/dajobe/redland-bindings
  git_rev: master
build:
  number: 0
requirements:
  build:
    - python
    - setuptools
    - librdf
    - swig
  run:
    - python
    - librdf
test:
  imports:
    - RDF 
about:
  home: https://github.com/dajobe/redland-bindings
  license: Apache2
